### ISSUE TITLE
App not working anymore on Jolla Sailfish OS 2.0

### ISSUE THREAD

**Issue by thargoid0815** [krobelus/cyanide#35]
I just noticed that the application does not work anymore
on Sailfish OS 2.0.

My setup is a Jolla Phone, Sailfish OS 2.0 (2.0.5.6, fresh install),
using cyanide 0.2.5.1-1 from openrepos.net via Warehouse.

The error manifests itself when tapping on your user name.
At that point the application freezes completely and can
only be killed. So it is not possible to use/setup the application
anymore.

**Comment by krobelus** [comment]
Hi, thank you for reporting this

I uploaded a current version on openrepos just now, which was long overdue.
It should work now on SFOS 2.0 - though notifications are not working properly atm.
Now all dependencies are bundled within the app, hence the huge size (Maybe I should add something that uninstalls the now unused libraries like toxcore).

Also audio calls should work :)

**Comment by thargoid0815** [comment]
That was really quick!

I just tried it, but it's still the same.
When I touch the default user on the overview screen
the app freezes. 

If I don't do anything, I can see that it connects though, 
that is, it switches to 'green'

**Comment by krobelus** [comment]
hmm I'm not sure why this happens for you

maybe you can get a useful log (if you start cyanide from the terminal)

freezes means that CPU usage goes to 100% I guess?
renaming `~/.config/tox` might also help (so that a new profile is created)

**Comment by thargoid0815** [comment]
Interesting...

If I start it via the cli, it does work!

And it is not the developer-mode... 
After installing the developer-mode and
trying to start it by tapping it freezes again.

Strange...

**Comment by thargoid0815** [comment]
Sorry, I didn't respond to all the points.

Yes, the CPU usage goes up to 100%.

And I completely deleted the .config/tox directory, created new ids, etc.
Does not work if I use the gui.

**Comment by thargoid0815** [comment]
After another complete reinstall of the phone it does work!

As a sidenote:
I did a full reset of the phone, patched it up to 2.0.5.6 and then tried to install cyanide as the first application. It seems that there is a dependency on an old version of OpenAL in the package.
This usually is of no consequence, because installation of the Jolla Media App comes with a newer version of OpenAL, so this dependency is fulfilled.

Sorry for the excitement and thanks for the update!!!

**Comment by krobelus** [comment]
Still a bit strange ;)
OpenAL is specified without any version constraint in cyanide.yaml, so it should install the most recent one.. I'm not entirely sure though
